### ISSUE TITLE
Automatic doc build failing

### ISSUE THREAD

**Issue by amilsted** [qojulia/QuantumOptics.jl-documentation#18] opened 2024-06-20 20:16 UTC
Hi @david-pl, it looks like the build/deploy workflow is failing because of a matplotlib error at the moment. Have you seen this before?

**Comment by Krastanov** [comment] 2024-06-20 20:48
suspicious that a breaking release of numpy was released last week (for the first time in a decade)

**Comment by david-pl** [comment] 2024-06-22 12:06
Hm odd, no haven't seen that before. Did anybody try building this locally?

**Comment by david-pl** [comment] 2024-06-27 18:13
Looks like the issue is actually a new matplotlib version and a call by PyPlot to an outdated API. The fix is already merged in PyPlot (https://github.com/JuliaPy/PyPlot.jl/pull/583), but there's no patch release yet.

I "fixed" it for now in #19 by pinning matplotlib to 3.8. In the long term, we should probably change to a different plotting library for the examples, but for now it's fine I suppose.

**Comment by david-pl** [comment] 2024-06-27 18:39
FYI, the successful run in the PR already deployed the latest version of the docs. I'll leave the PR dangling for a few days and merge then if there are no comments.

**Comment by amilsted** [comment] 2024-06-27 20:34
Looks good to me!

**Comment by amilsted** [comment] 2024-06-27 20:34
Thanks for fixing this.

**Closed** 2024-07-11 15:53 UTC
